# Generated by Django 5.0.6 on 2024-06-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interno', '0002_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('razao_social', models.CharField(max_length=100, unique=True)),
                ('inscricao_estadual', models.CharField(max_length=9, unique=True)),
            ],
        ),
    ]
