# Generated by Django 5.0.6 on 2024-06-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interno', '0003_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='colaboradores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='faturamento',
            field=models.FloatField(default=0),
        ),
    ]
